name: Build and Release

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Skip the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true      # Disable .NET CLI telemetry

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Setup Windows SDK
      uses: microsoft/setup-msbuild@v2

    - name: Publish
      run: |
        dotnet publish League_Account_Manager/League_Account_Manager.csproj `
          -c Release `
          --self-contained true `
          -r win-x64 `
          -p:PublishSingleFile=true `
          -p:EnableWindowsTargeting=true `
          -p:WindowsPackageType=None `
          -p:Version=${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || '1.0.0-dev' }} `
          -p:NoWarn=CA1416

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        name: "Release ${{ github.ref_name }}"
        body: |
          ## Changes in version ${{ github.ref_name }}
          
          ${{ github.event.head_commit.message }}
          
          ## Details
          - Single-file executable for Windows
          - Self-contained (no .NET installation required)
          - Transparent, non-obfuscated code
          
          ## Note
          This is a clear, transparent fork of the League Account Manager. The complete source code is available for review.
          
        files: |
          League_Account_Manager/bin/Release/net7.0-windows/win-x64/publish/*.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
