name: Build and Release

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Setup Windows SDK
      uses: microsoft/setup-msbuild@v2

    - name: Set Version
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        $version = "${{ github.ref }}".Replace('refs/tags/v', '')
        echo "BUILD_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Publish
      run: |
        dotnet publish League_Account_Manager/League_Account_Manager.csproj `
          -c Release `
          --self-contained true `
          -r win-x64 `
          -p:PublishSingleFile=true `
          -p:EnableWindowsTargeting=true `
          -p:WindowsPackageType=None `
          -p:Version=${{ env.BUILD_VERSION || '1.0.0' }} `
          -p:NoWarn=CA1416

    # Add a step to verify the executable exists and show its location
    - name: List Published Files
      run: |
        dir League_Account_Manager\bin\Release\net7.0-windows\win-x64\publish\ /s

    # Create a zip of the published files
    - name: Create Release Zip
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        Compress-Archive -Path "League_Account_Manager\bin\Release\net7.0-windows\win-x64\publish\*" -DestinationPath "Release.zip"

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        name: "Release ${{ github.ref_name }}"
        body: |
          ## Changes in version ${{ env.BUILD_VERSION }}
          
          ${{ github.event.head_commit.message }}
          
          ## Details
          - Single-file executable for Windows
          - Self-contained (no .NET installation required)
          - Transparent, non-obfuscated code
          
          ## Note
          This is a clear, transparent fork of the League Account Manager. The complete source code is available for review.
          
        files: |
          Release.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
